#!/bin/bash
gcc -O3 -Wall -Werror -o lab1-seq lab1.c -lm
gcc -O3 -Wall -Werror -floop-parallelize-all -ftree-parallelize-loops=1 lab1.c -o lab1-par-1 -lm
gcc -O3 -Wall -Werror -floop-parallelize-all -ftree-parallelize-loops=3 lab1.c -o lab1-par-3 -lm
gcc -O3 -Wall -Werror -floop-parallelize-all -ftree-parallelize-loops=6 lab1.c -o lab1-par-6 -lm
gcc -O3 -Wall -Werror -floop-parallelize-all -ftree-parallelize-loops=12 lab1.c -o lab1-par-12 -lm
gcc -O3 -Wall -Werror -floop-parallelize-all -ftree-parallelize-loops=24 lab1.c -o lab1-par-24 -lm
icc -parallel -par-threshold0 -par-num-threads=1 -o lab1-icc-par-1 lab1.c


